#! /usr/bin/env python
from os import system
from time import sleep
if __name__ == '__main__':
	system('echo 0 > /sys/devices/virtual/gpio/gpio145/value')
	sleep(.5)
	system('echo 1 > /sys/devices/virtual/gpio/gpio145/value')
	sleep(5)
